source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'CocoaLumberjack'
pod 'VCTransitionsLibrary'
pod 'IQKeyboardManager'
pod 'ReactiveCocoa'
pod 'Underscore.m'
pod 'AB_Framework', :git => 'https://github.com/abeck99/AB_Framework.git'
